"""
PARKDRONE Webots controller — autonomous street patrol + camera capture.

Flight stabilisation is adapted from Webots' official Mavic 2 PRO sample
(propeller-mixing PD on roll/pitch/altitude). On top of it we add a simple
waypoint navigator that turns toward the next waypoint then flies forward,
following the street bay-rows (worlds/route.json, built by generate_world.py;
falls back to a square lawnmower if absent) and saving a camera frame (plus
drone pose, for later georeferencing) at each waypoint.

UNTESTED outside Webots — device names assume the Mavic2Pro proto. Open
worlds/fmi_block.wbt in Webots to run; tune the constants there.
"""
import os, sys, math, json
from controller import Robot

HERE = os.path.dirname(__file__)
# The world hands us its route file via controllerArgs (see generate_world.py);
# the world's name derived from it keys the output folder, so flights of
# different worlds don't clobber each other's frames/poses.
ROUTE_FILE = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else "route.json"
WORLD = (ROUTE_FILE[:-len(".route.json")] if ROUTE_FILE.endswith(".route.json")
         else "fmi_block")
OUT = os.path.join(HERE, "..", "..", "output", WORLD)
WORLDS = os.path.join(HERE, "..", "..", "worlds")
os.makedirs(OUT, exist_ok=True)

TARGET_ALT = 30.0          # metres
WP_REACH = 6.0             # arrival basin (m); must stay generous or the drone
#   orbits waypoints it can't converge into. The frame is NOT taken on entering
#   the basin but at closest approach, so captures stay tight to the route:
#   arrive when really close (WP_CAPTURE), when receding 1 m past the closest
#   pass, or after WP_TIMEOUT near the waypoint. The timeout matters: at cruise
#   speed the turn radius is ~4 m, so the drone can settle into a stable ORBIT
#   inside the basin with constant distance - no distance-based test ever fires.
WP_CAPTURE = 2.5           # capture immediately once this close to the waypoint
WP_TIMEOUT = 8.0           # s near the waypoint before capturing anyway (orbit)
AIM_BLEND = 15.0           # m: within this range of the current waypoint the
#   nose aims progressively at the NEXT one (carrot / pure-pursuit style), so
#   straight legs flow through the 10 m waypoints without a stop-and-turn at
#   each hand-off (the drone visibly "danced" its yaw every waypoint without
#   this). Arrival/capture still keys off the CURRENT waypoint distance, and
#   at route reversals the blended aim swings behind -> yaw gate brakes the
#   drone and it U-turns on the spot, same as before.
LANE_STEP = 25.0           # spacing between lawnmower lanes (fallback only)
HALF = 65.0                # window half-size to cover (fallback only)


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def wrap(a):
    return (a + math.pi) % (2 * math.pi) - math.pi


def lawnmower(half, step):
    wps, y, going_right = [], -half, True
    while y <= half:
        xs = [-half, half] if going_right else [half, -half]
        for x in xs:
            wps.append((x, y))
        y += step
        going_right = not going_right
    return wps


def load_route():
    """Waypoints that follow the streets, generated by generate_world.py (in
    the same local metres as the world). The world passes its own route file
    via controllerArgs (e.g. fmi_block_1km.route.json) so several worlds can
    coexist in worlds/; default is the legacy route.json. Fall back to a blind
    square lawnmower if the file is missing."""
    path = os.path.join(WORLDS, ROUTE_FILE)
    try:
        wps = [tuple(p) for p in json.load(open(path, encoding="utf-8"))]
        if wps:
            print(f"[parkdrone] loaded {len(wps)} route waypoints from {path}")
            return wps
        print(f"[parkdrone] !! {path} is empty -> falling back to lawnmower")
    except (OSError, ValueError) as e:
        print(f"[parkdrone] !! no usable {ROUTE_FILE} ({e}) -> lawnmower fallback")
    return lawnmower(HALF, LANE_STEP)


robot = Robot()
dt = int(robot.getBasicTimeStep())

camera = robot.getDevice("camera"); camera.enable(dt)
imu = robot.getDevice("inertial unit"); imu.enable(dt)
gps = robot.getDevice("gps"); gps.enable(dt)
gyro = robot.getDevice("gyro"); gyro.enable(dt)
cam_roll = robot.getDevice("camera roll")
cam_pitch = robot.getDevice("camera pitch")
# DIAGNOSTIC: confirm the gimbal devices exist and report their real tilt range.
# An all-sky frame means the camera never tilts down — usually because these
# device names don't match the proto, so cam_pitch stays None and we never tilt.
print(f"[parkdrone] camera res {camera.getWidth()}x{camera.getHeight()} "
      f"fov={camera.getFov():.3f}")
if cam_pitch is None:
    print("[parkdrone] !! 'camera pitch' device NOT FOUND — gimbal will stay "
          "horizontal (sky-only frames). Check the proto node tree for the name.")
else:
    print(f"[parkdrone] gimbal pitch range "
          f"[{cam_pitch.getMinPosition():.3f}, {cam_pitch.getMaxPosition():.3f}] rad "
          f"(DOWN is positive on this proto; +pi/2 = nadir)")
if cam_roll is None:
    print("[parkdrone] !! 'camera roll' device NOT FOUND")

motors = [robot.getDevice(n) for n in
          ("front left propeller", "front right propeller",
           "rear left propeller", "rear right propeller")]
for m in motors:
    m.setPosition(float("inf")); m.setVelocity(1.0)

# control gains (from the Webots Mavic sample)
K_VT = 68.5; K_VOFF = 0.6; K_VP = 3.0; K_ROLL = 50.0; K_PITCH = 30.0
K_YAW = 1.0; K_YAWD = 0.8                    # heading PD: point the nose at the
#   waypoint. K_YAWD damps yaw RATE -- without it the yaw is pure-proportional and
#   the drone spins in circles past the target heading, never converging.
K_VD = 2.0                                  # vertical-velocity damping (kills overshoot)
# Horizontal navigation: body-frame position+velocity PD -> roll/pitch tilt.
# Pull toward the waypoint (K_POS) while damping ground velocity (K_VEL) so the
# drone decelerates into the target instead of orbiting it (the old bug).
K_POS = 0.6; K_VEL = 0.4; TILT_MAX = 1.0     # TILT_MAX>~1.0 dips lift -> crash
V_MAX = 2.5                                   # cruise-speed cap (m/s); lower = tighter turns
#   (tried 2.0 hoping tighter waypoint captures -> no coverage gain, just slower)
ROLL_SIGN = 1.0                             # +roll_in -> +body-left; flip if it diverges

dt_s = dt / 1000.0
prev_xy = None
prev_alt = None
wp_min = float("inf")     # closest approach to the current waypoint so far
wp_steps = 0              # steps spent near the current waypoint
wps = load_route()
idx = 0
poses = []
step = 0
snap = 0                          # timed-snapshot counter (diagnostic capture)
HEARTBEAT = max(1, int(1.0 / dt_s))      # ~1 s of steps
SNAP_EVERY = max(1, int(3.0 / dt_s))     # save a frame every ~3 s once airborne
print(f"[parkdrone] {len(wps)} waypoints, target alt {TARGET_ALT} m, "
      f"frames -> {os.path.abspath(OUT)}")


def capture(path):
    """Save a camera frame; saveImage returns 0 on success, -1 on failure."""
    rc = camera.saveImage(path, 90)
    if rc != 0:
        print(f"[parkdrone] !! saveImage FAILED rc={rc} path={path}")
    return rc == 0


while robot.step(dt) != -1:
    step += 1
    roll, pitch, yaw = imu.getRollPitchYaw()
    x, y, alt = gps.getValues()
    roll_rate, pitch_rate, yaw_rate = gyro.getValues()

    if step % HEARTBEAT == 0:
        if idx < len(wps):
            d = math.hypot(wps[idx][0] - x, wps[idx][1] - y)
            ye = wrap(math.atan2(wps[idx][1] - y, wps[idx][0] - x) - yaw)
        else:
            d = ye = 0.0
        print(f"[parkdrone] t={step*dt_s:6.1f}s alt={alt:6.2f} "
              f"pos=({x:7.1f},{y:7.1f}) wp{idx}/{len(wps)} dist={d:6.1f} "
              f"yaw_err={ye:+5.2f} airborne={'Y' if alt > TARGET_ALT - 1.0 else 'n'}")

    # horizontal velocity (finite difference from GPS) for damping
    if prev_xy is None:
        vx = vy = 0.0
    else:
        vx = (x - prev_xy[0]) / dt_s
        vy = (y - prev_xy[1]) / dt_s
    prev_xy = (x, y)
    vz = (alt - prev_alt) / dt_s if prev_alt is not None else 0.0
    prev_alt = alt

    # Point the gimbal straight down (nadir). On the stock Mavic2Pro proto DOWN
    # is the POSITIVE pitch direction (range ~[-0.5, +1.7]), so +pi/2 is true
    # nadir. The old code used getMinPosition() (-0.5) which tilts the camera UP
    # ~29 deg -> sky-only frames. We clamp +pi/2 into the device range to be safe.
    if cam_pitch is not None:
        cam_pitch.setPosition(clamp(math.pi / 2,
                                    cam_pitch.getMinPosition(),
                                    cam_pitch.getMaxPosition()))
    if cam_roll is not None:
        cam_roll.setPosition(clamp(-0.115 * roll,
                                   cam_roll.getMinPosition(),
                                   cam_roll.getMaxPosition()))

    # diagnostic: once airborne, save a frame on a timer regardless of nav,
    # so we can confirm the camera works even if the lawnmower isn't converging.
    if alt > TARGET_ALT - 1.0 and step % SNAP_EVERY == 0:
        if capture(os.path.join(OUT, f"snap_{snap:03d}.png")):
            print(f"[parkdrone] snapshot snap_{snap:03d}.png at alt {alt:.1f}")
        snap += 1

    # Only start steering toward waypoints once altitude has actually settled
    # (near target AND not climbing/falling fast). Pitching forward mid-climb is
    # what tumbled the drone into the ground before.
    settled = abs(TARGET_ALT - alt) < 1.5 and abs(vz) < 0.8
    roll_d = pitch_d = yaw_d = 0.0
    if settled:
        # body-frame ground velocity (used for speed control + drift damping)
        c, s = math.cos(yaw), math.sin(yaw)
        fwd_vel =  c * vx + s * vy
        lat_vel = -s * vx + c * vy
        if idx < len(wps):
            tx, ty = wps[idx]
            dx, dy = tx - x, ty - y
            dist = math.hypot(dx, dy)
            # capture at CLOSEST APPROACH, not on first basin entry (which put
            # the capture up to WP_REACH metres off-route and skipped edge bays)
            near = dist < WP_REACH
            if near or wp_min < float("inf"):
                wp_steps += 1
                if near:
                    wp_min = min(wp_min, dist)
            arrived = (near and (dist < WP_CAPTURE or dist > wp_min + 1.0)) or \
                      (wp_min < float("inf") and wp_steps * dt_s > WP_TIMEOUT)
            if arrived:
                wp_min = float("inf")
                wp_steps = 0
                capture(os.path.join(OUT, f"frame_{idx:03d}.png"))
                poses.append({"i": idx, "x": x, "y": y, "alt": alt, "yaw": yaw,
                              "wp": [tx, ty]})
                # write poses.json after every waypoint so progress survives even
                # if the run is cut short before the full patrol completes.
                json.dump(poses, open(os.path.join(OUT, "poses.json"), "w"), indent=1)
                print(f"[parkdrone] reached wp{idx} at ({x:.1f},{y:.1f}) "
                      f"-> frame_{idx:03d}.png")
                idx += 1
                if idx == len(wps):
                    print("[parkdrone] patrol complete")
            else:
                # aim point: the current waypoint, blending toward the next one
                # as we close in, so the nose flows through waypoint hand-offs
                ax, ay = tx, ty
                if idx + 1 < len(wps) and dist < AIM_BLEND:
                    t_b = 1.0 - dist / AIM_BLEND
                    ax += (wps[idx + 1][0] - tx) * t_b
                    ay += (wps[idx + 1][1] - ty) * t_b
                # heading PD: point the nose at the aim point (steer like a car;
                # we do NOT strafe with roll, which would tumble the drone).
                yaw_err = wrap(math.atan2(ay - y, ax - x) - yaw)
                yaw_d = clamp(K_YAW * yaw_err - K_YAWD * yaw_rate, -1.0, 1.0)
                fwd_err = c * dx + s * dy
                # Velocity-target forward control: desired speed ramps DOWN within
                # ~V_MAX/K_POS metres of the target (and is 0 until we're facing
                # it), so the drone arrives slow and turns tightly at row ends
                # instead of coasting tens of metres past. Roll just damps drift.
                v_des = clamp(K_POS * fwd_err, 0.0, V_MAX) if abs(yaw_err) < 0.5 else 0.0
                pitch_d = -clamp(K_VEL * (v_des - fwd_vel), -TILT_MAX, TILT_MAX)
                roll_d = ROLL_SIGN * clamp(-K_VEL * lat_vel, -TILT_MAX, TILT_MAX)
        else:
            # Patrol done: station-keep by braking horizontal drift, otherwise the
            # drone slowly sails away (km-scale) with no control input.
            pitch_d = -clamp(-K_VEL * fwd_vel, -TILT_MAX, TILT_MAX)
            roll_d = ROLL_SIGN * clamp(-K_VEL * lat_vel, -TILT_MAX, TILT_MAX)

    # propeller mixing
    roll_in = K_ROLL * clamp(roll, -1, 1) + roll_rate + roll_d
    pitch_in = K_PITCH * clamp(pitch, -1, 1) + pitch_rate + pitch_d
    yaw_in = yaw_d
    vert = K_VP * clamp(TARGET_ALT - alt + K_VOFF, -1, 1) ** 3 - K_VD * vz

    motors[0].setVelocity(K_VT + vert - roll_in + pitch_in - yaw_in)   # front-left
    motors[1].setVelocity(-(K_VT + vert + roll_in + pitch_in + yaw_in))  # front-right
    motors[2].setVelocity(-(K_VT + vert - roll_in - pitch_in + yaw_in))  # rear-left
    motors[3].setVelocity(K_VT + vert + roll_in - pitch_in - yaw_in)   # rear-right
