"""
PARKDRONE Webots controller — autonomous street patrol + camera capture.

Flight stabilisation is adapted from Webots' official Mavic 2 PRO sample
(propeller-mixing PD on roll/pitch/altitude). On top of it we add a simple
waypoint navigator that turns toward the next waypoint then flies forward,
following the street bay-rows (worlds/route.json, built by generate_world.py;
falls back to a square lawnmower if absent) and saving a camera frame (plus
drone pose, for later georeferencing) at each waypoint.

UNTESTED outside Webots — device names assume the Mavic2Pro proto. Open
worlds/fmi_block.wbt in Webots to run; tune the constants there.
"""
import os, sys, math, json
from controller import Robot

HERE = os.path.dirname(__file__)
# The world hands us its route file via controllerArgs (see generate_world.py);
# the survey area named by it keys the output folder, so flights over
# different areas don't clobber each other's frames/poses.
ROUTE_FILE = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else "route.json"
SURVEY_AREA = (ROUTE_FILE[:-len(".route.json")] if ROUTE_FILE.endswith(".route.json")
               else "fmi_block")
OUT = os.path.join(HERE, "..", "..", "output", SURVEY_AREA)
WORLDS = os.path.join(HERE, "..", "..", "worlds")
os.makedirs(OUT, exist_ok=True)

TARGET_ALT = 30.0          # metres
WP_REACH = 6.0             # arrival basin (m); must stay generous or the drone
#   orbits waypoints it can't converge into. The frame is NOT taken on entering
#   the basin but at closest approach, so captures stay tight to the route:
#   arrive when really close (WP_CAPTURE), when receding 1 m past the closest
#   pass, or after WP_TIMEOUT near the waypoint. The timeout matters: at cruise
#   speed the turn radius is ~4 m, so the drone can settle into a stable ORBIT
#   inside the basin with constant distance - no distance-based test ever fires.
WP_CAPTURE = 2.5           # capture immediately once this close to the waypoint
WP_TIMEOUT = 8.0           # s near the waypoint before capturing anyway (orbit)
AIM_BLEND = 15.0           # m: within this range of the current waypoint the
#   nose aims progressively at the NEXT one (carrot / pure-pursuit style), so
#   straight legs flow through the 10 m waypoints without a stop-and-turn at
#   each hand-off (the drone visibly "danced" its yaw every waypoint without
#   this). Arrival/capture still keys off the CURRENT waypoint distance, and
#   at route reversals the blended aim swings behind -> yaw gate brakes the
#   drone and it U-turns on the spot, same as before.
LANE_STEP = 25.0           # spacing between lawnmower lanes (fallback only)
HALF = 65.0                # window half-size to cover (fallback only)


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def wrap(a):
    return (a + math.pi) % (2 * math.pi) - math.pi


def lawnmower(half, step):
    wps, y, going_right = [], -half, True
    while y <= half:
        xs = [-half, half] if going_right else [half, -half]
        for x in xs:
            wps.append((x, y))
        y += step
        going_right = not going_right
    return wps


def load_route():
    """Waypoints that follow the streets, generated by generate_world.py (in
    the same local metres as the world). The world passes its own route file
    via controllerArgs (e.g. fmi_block_1km.route.json) so several survey areas
    can coexist in worlds/; default is the legacy route.json. Fall back to a blind
    square lawnmower if the file is missing."""
    path = os.path.join(WORLDS, ROUTE_FILE)
    try:
        wps = [tuple(p) for p in json.load(open(path, encoding="utf-8"))]
        if wps:
            print(f"[parkdrone] loaded {len(wps)} route waypoints from {path}")
            return wps
        print(f"[parkdrone] !! {path} is empty -> falling back to lawnmower")
    except (OSError, ValueError) as e:
        print(f"[parkdrone] !! no usable {ROUTE_FILE} ({e}) -> lawnmower fallback")
    return lawnmower(HALF, LANE_STEP)


robot = Robot()
dt = int(robot.getBasicTimeStep())

camera = robot.getDevice("camera")
# The camera is NOT enabled continuously: at basicTimeStep 8 ms an enabled
# camera re-renders 125 frames/s that nobody reads, and that rendering
# dominates wall time in --mode=fast (the sim barely beat real time on the
# 4-street world). Instead the camera is enabled on waypoint arrival, given
# CAM_WARMUP steps to produce a fresh image, saved, then disabled again.
# Pose is recorded at the save step, so image/pose mismatch stays <= one
# basic time step (~4 cm at 5 m/s) — same as with continuous sampling.
CAM_WARMUP = 2             # steps between camera.enable() and saveImage()
cam_warm = -1              # >=0 while a capture is scheduled (counts down)
SNAP_DIAG = True           # timed snap_###.png diagnostics need a continuously
#   enabled camera; turn back on only when debugging capture itself.
if SNAP_DIAG:
    camera.enable(dt)
imu = robot.getDevice("inertial unit"); imu.enable(dt)
gps = robot.getDevice("gps"); gps.enable(dt)
gyro = robot.getDevice("gyro"); gyro.enable(dt)
cam_roll = robot.getDevice("camera roll")
cam_pitch = robot.getDevice("camera pitch")
# DIAGNOSTIC: confirm the gimbal devices exist and report their real tilt range.
# An all-sky frame means the camera never tilts down — usually because these
# device names don't match the proto, so cam_pitch stays None and we never tilt.
print(f"[parkdrone] camera res {camera.getWidth()}x{camera.getHeight()} "
      f"fov={camera.getFov():.3f}")
if cam_pitch is None:
    print("[parkdrone] !! 'camera pitch' device NOT FOUND — gimbal will stay "
          "horizontal (sky-only frames). Check the proto node tree for the name.")
else:
    print(f"[parkdrone] gimbal pitch range "
          f"[{cam_pitch.getMinPosition():.3f}, {cam_pitch.getMaxPosition():.3f}] rad "
          f"(DOWN is positive on this proto; +pi/2 = nadir)")
if cam_roll is None:
    print("[parkdrone] !! 'camera roll' device NOT FOUND")

# The gimbal compensation command (pi/2 - pitch) is only as good as the servo
# tracking it: captures fire at waypoint arrival, i.e. right after braking,
# when body pitch has just swung hard and the servo may still lag its target
# by tens of milliradians -- at 30 m altitude 0.03 rad off-nadir shifts the
# ground footprint ~1 m and misprojects bays near the frame edge. Record the
# ACTUAL gimbal angles (position sensors, if the proto exposes them) with each
# pose so the scorer can correct the projection instead of assuming nadir.
def _gimbal_sensor(motor, label):
    if motor is None:
        return None
    sensor = motor.getPositionSensor()
    if sensor is None:
        print(f"[parkdrone] !! no position sensor on '{label}' - poses will "
              f"not carry actual gimbal angles")
        return None
    sensor.enable(dt)
    return sensor

cam_pitch_pos = _gimbal_sensor(cam_pitch, "camera pitch")
cam_roll_pos = _gimbal_sensor(cam_roll, "camera roll")
# The proto also has an uncommanded "camera yaw" joint resting at 0; its servo
# can transiently deflect during hard yaw maneuvers (captures at corners), and
# the scorer assumes camera yaw == body yaw. Record the actual joint angle.
cam_yaw = robot.getDevice("camera yaw")
cam_yaw_pos = _gimbal_sensor(cam_yaw, "camera yaw")

motors = [robot.getDevice(n) for n in
          ("front left propeller", "front right propeller",
           "rear left propeller", "rear right propeller")]
for m in motors:
    m.setPosition(float("inf")); m.setVelocity(1.0)

# control gains (from the Webots Mavic sample)
K_VT = 68.5; K_VOFF = 0.6; K_VP = 3.0; K_ROLL = 50.0; K_PITCH = 30.0
K_YAW = 1.0; K_YAWD = 0.8                    # heading PD: point the nose at the
#   waypoint. K_YAWD damps yaw RATE -- without it the yaw is pure-proportional and
#   the drone spins in circles past the target heading, never converging.
K_VD = 2.0                                  # vertical-velocity damping (kills overshoot)
# Horizontal navigation: velocity-target control -> roll/pitch tilt. Chase a
# desired forward speed (from the corner-aware profile below) while damping
# ground velocity (K_VEL) so the drone decelerates into corners instead of
# orbiting waypoints (the old bug).
K_VEL = 0.4; TILT_MAX = 1.0                  # TILT_MAX>~1.0 dips lift -> crash
# Corner-aware cruise speed. A flat cap is a bad trade: 2.5 m/s is safe
# everywhere but slow on straights, while a flat 5.0 CRASHED the 1 km patrol
# at wp645 -- entering a sharp junction turn at full speed saturates brake
# pitch + yaw + drift-damping roll all at once and the lift dip tumbles the
# drone (the 4-street route never reaches 5 m/s before a corner, so it can't
# catch this). So the cap now depends on the route geometry: every waypoint
# gets a speed limit from its heading change (V_MAX when straight, down to
# V_TURN for sharp corners), and a backward pass propagates each limit
# upstream along the real kinematic braking curve (A_BRAKE, below) so
# braking starts early enough -- the drone cruises the straights at V_MAX
# and arrives at corners at the speed the 2.5 m/s patrols proved safe.
V_MAX = 5.0                # cruise speed on straight legs (m/s)
V_TURN = 2.0               # arrival speed at sharp corners (~90 deg)
TURN_FREE = 0.3            # rad heading change below which a wp is "straight"
TURN_HARD = 1.2            # rad heading change at which the full V_TURN applies
# Route REVERSALS (~180 deg, end of a bay row) get a still lower arrival
# speed: braking tops out at ~0.29 m/s^2, so overshoot past the turn point
# scales with v^2/(2*0.29) -- at V_TURN 2.0 the drone coasted ~7 m past the
# reversal while yawing round and had to fly back (a visible teardrop loop);
# at 0.8 m/s the excursion is ~1 m, i.e. it turns essentially on the spot.
V_REV = 0.8                # arrival speed at reversals (turn ~in place)
REV_HARD = 2.6             # rad heading change treated as a full reversal
# Full stop before big turns: even at V_REV the residual momentum coasts ~1 m
# through the pirouette. If the heading change to the NEXT waypoint (measured
# at capture) exceeds HOLD_TURN, hold zero forward command until ground speed
# falls below HOLD_SPEED -- the drone brakes to a hover, spins in place, then
# accelerates out on the new heading.
HOLD_TURN = 1.5            # rad yaw change that triggers a stop-and-turn
HOLD_SPEED = 0.15          # m/s ground speed that counts as "stopped"
# A_BRAKE is the vehicle's REAL achievable accel/decel, measured from a 1 km
# headless run's GPS log (poses/heartbeat), not assumed: velocity-vs-time
# showed ~12-14 s to go from ~3.6 m/s to ~0.1 m/s (and back), i.e. ~0.29 m/s^2
# -- TILT_MAX=1.0 caps the equilibrium tilt angle (pitch_d/K_PITCH ~ 2 deg),
# and there is no aerodynamic drag in the sim, so this is a hard ceiling, not
# a gain-tuning artifact. The old linear K_BRAKE=0.25 model assumed decel
# "<=1.25 m/s^2" (5x too strong): it started braking only ~12 m out for a
# 5->2 m/s drop that actually needs ~36 m, so the drone blew through every
# waypoint near cruise speed, the AIM_BLEND carrot swung hard toward the next
# point, and -- since steering is yaw-then-forward only, no reverse/strafe --
# it had to bleed the overshoot off in a wide loop instead of flowing
# through. Fixed by planning against the real KINEMATIC curve
# v(dist) = sqrt(v_target^2 + 2*A_BRAKE*dist) instead of a linear ramp, with
# a small safety margin below the measured 0.29 m/s^2.
A_BRAKE = 0.22             # m/s^2, conservative vs. the ~0.29 measured


def speed_profile(wps):
    """Per-waypoint speed limit: corner limit from the route's heading change,
    then a backward pass so the kinematic braking curve (v^2 = v_next^2 +
    2*A_BRAKE*dist) is announced early enough upstream (junction segments can
    be much shorter than the 10 m route step)."""
    n = len(wps)
    prof = [V_TURN] * n     # last wp stays slow (patrol ends station-keeping)
    for i in range(n - 1):
        # wp0 has no route leg in: use the takeoff spawn (world origin) as the
        # virtual previous point, so its corner limit reflects the real turn-in
        # instead of a blanket V_TURN.
        px, py = wps[i - 1] if i > 0 else (0.0, 0.0)
        if (px, py) == wps[i]:
            continue
        h_in = math.atan2(wps[i][1] - py, wps[i][0] - px)
        h_out = math.atan2(wps[i+1][1] - wps[i][1], wps[i+1][0] - wps[i][0])
        turn = abs(wrap(h_out - h_in))
        if turn <= TURN_HARD:
            f = clamp((turn - TURN_FREE) / (TURN_HARD - TURN_FREE), 0.0, 1.0)
            prof[i] = V_MAX - f * (V_MAX - V_TURN)
        else:   # beyond a hard corner: ramp further down toward reversal speed
            f = clamp((turn - TURN_HARD) / (REV_HARD - TURN_HARD), 0.0, 1.0)
            prof[i] = V_TURN - f * (V_TURN - V_REV)
    for i in range(n - 2, -1, -1):
        seg = math.hypot(wps[i+1][0] - wps[i][0], wps[i+1][1] - wps[i][1])
        prof[i] = min(prof[i], math.sqrt(prof[i+1]**2 + 2 * A_BRAKE * seg))
    return prof


ROLL_SIGN = 1.0                             # +roll_in -> +body-left; flip if it diverges

dt_s = dt / 1000.0
prev_xy = None
prev_alt = None
wp_min = float("inf")     # closest approach to the current waypoint so far
wp_steps = 0              # steps spent near the current waypoint
hold_stop = False         # braking to a hover before a stop-and-turn reversal
wps = load_route()
wp_vmax = speed_profile(wps)
n_slow = sum(1 for v in wp_vmax if v < V_MAX - 0.01)
print(f"[parkdrone] corner speed profile: {n_slow}/{len(wps)} waypoints "
      f"below V_MAX {V_MAX} (corner floor {V_TURN} m/s)")
# RESUME: poses.json is rewritten after every capture, so if a long patrol is
# interrupted (crash, kill, host sleep) the flight can continue where it left
# off: load the recorded poses and start from the first uncaptured waypoint.
# Delete poses.json (or the survey area's output dir) to re-fly from scratch.
idx = 0
poses = []
POSES_FILE = os.path.join(OUT, "poses.json")
try:
    poses = json.load(open(POSES_FILE, encoding="utf-8"))
except (OSError, ValueError):
    poses = []
if poses:
    idx = max(p["i"] for p in poses) + 1
    print(f"[parkdrone] RESUME: {len(poses)} captures on disk -> "
          f"continuing at wp{idx}/{len(wps)}")
step = 0
snap = 0                          # timed-snapshot counter (diagnostic capture)
HEARTBEAT = max(1, int(1.0 / dt_s))      # ~1 s of steps
SNAP_EVERY = max(1, int(3.0 / dt_s))     # save a frame every ~3 s once airborne
print(f"[parkdrone] {len(wps)} waypoints, target alt {TARGET_ALT} m, "
      f"frames -> {os.path.abspath(OUT)}")


def capture(path):
    """Save a camera frame; saveImage returns 0 on success, -1 on failure."""
    rc = camera.saveImage(path, 90)
    if rc != 0:
        print(f"[parkdrone] !! saveImage FAILED rc={rc} path={path}")
    return rc == 0


while robot.step(dt) != -1:
    step += 1
    roll, pitch, yaw = imu.getRollPitchYaw()
    x, y, alt = gps.getValues()
    roll_rate, pitch_rate, yaw_rate = gyro.getValues()

    if step % HEARTBEAT == 0:
        if idx < len(wps):
            d = math.hypot(wps[idx][0] - x, wps[idx][1] - y)
            ye = wrap(math.atan2(wps[idx][1] - y, wps[idx][0] - x) - yaw)
        else:
            d = ye = 0.0
        print(f"[parkdrone] t={step*dt_s:6.1f}s alt={alt:6.2f} "
              f"pos=({x:7.1f},{y:7.1f}) wp{idx}/{len(wps)} dist={d:6.1f} "
              f"yaw_err={ye:+5.2f} airborne={'Y' if alt > TARGET_ALT - 1.0 else 'n'}")

    # horizontal velocity (finite difference from GPS) for damping
    if prev_xy is None:
        vx = vy = 0.0
    else:
        vx = (x - prev_xy[0]) / dt_s
        vy = (y - prev_xy[1]) / dt_s
    prev_xy = (x, y)
    vz = (alt - prev_alt) / dt_s if prev_alt is not None else 0.0
    prev_alt = alt

    # Point the gimbal straight down (nadir). On the stock Mavic2Pro proto DOWN
    # is the POSITIVE pitch direction (range ~[-0.5, +1.7]), so +pi/2 is true
    # nadir. The old code used getMinPosition() (-0.5) which tilts the camera UP
    # ~29 deg -> sky-only frames. We clamp into the device range to be safe.
    # The gimbal angles are BODY-relative, so the body attitude must be
    # subtracted out: a fixed +pi/2 left the camera off-nadir by the cruise
    # pitch (~2 deg = ~1 m footprint shift at 30 m), which showed up as bay
    # polygons misprojected onto the neighbouring bay in the occupancy scoring.
    if cam_pitch is not None:
        cam_pitch.setPosition(clamp(math.pi / 2 - pitch,
                                    cam_pitch.getMinPosition(),
                                    cam_pitch.getMaxPosition()))
    if cam_roll is not None:
        cam_roll.setPosition(clamp(-roll,
                                   cam_roll.getMinPosition(),
                                   cam_roll.getMaxPosition()))

    # diagnostic: once airborne, save a frame on a timer regardless of nav,
    # so we can confirm the camera works even if the lawnmower isn't converging.
    if SNAP_DIAG and alt > TARGET_ALT - 1.0 and step % SNAP_EVERY == 0:
        if capture(os.path.join(OUT, f"snap_{snap:03d}.png")):
            print(f"[parkdrone] snapshot snap_{snap:03d}.png at alt {alt:.1f}")
        snap += 1

    # Only start steering toward waypoints once altitude has actually settled
    # (near target AND not climbing/falling fast). Pitching forward mid-climb is
    # what tumbled the drone into the ground before.
    settled = abs(TARGET_ALT - alt) < 1.5 and abs(vz) < 0.8
    roll_d = pitch_d = yaw_d = 0.0
    if settled:
        # body-frame ground velocity (used for speed control + drift damping)
        c, s = math.cos(yaw), math.sin(yaw)
        fwd_vel =  c * vx + s * vy
        lat_vel = -s * vx + c * vy
        if idx < len(wps):
            tx, ty = wps[idx]
            dx, dy = tx - x, ty - y
            dist = math.hypot(dx, dy)
            # capture at CLOSEST APPROACH, not on first basin entry (which put
            # the capture up to WP_REACH metres off-route and skipped edge bays)
            near = dist < WP_REACH
            if near or wp_min < float("inf"):
                wp_steps += 1
                if near:
                    wp_min = min(wp_min, dist)
            # Recede fires WITHOUT requiring dist < WP_REACH: when the closest
            # pass is near the basin edge (e.g. 5 m at cruise speed), the drone
            # is already outside the basin by the time it has receded 1 m, the
            # basin-gated test can never fire, and the orbit TIMEOUT ends up
            # taking the frame wherever the recovery loop happens to be (27 m
            # off-waypoint in the worst observed case). Ungated, the capture
            # distance is bounded by closest-approach + 1 m <= WP_REACH + 1.
            arrived = (dist < WP_CAPTURE) or \
                      (wp_min < float("inf") and
                       (dist > wp_min + 1.0 or wp_steps * dt_s > WP_TIMEOUT))
            if cam_warm >= 0:
                # capture scheduled on a previous step: give the just-enabled
                # camera CAM_WARMUP steps to render, then save frame + pose
                # together (drone drifts ~4 cm/step meanwhile — negligible).
                cam_warm -= 1
                if cam_warm < 0:
                    capture(os.path.join(OUT, f"frame_{idx:03d}.png"))
                    pose = {"i": idx, "x": x, "y": y, "alt": alt, "yaw": yaw,
                            "roll": roll, "pitch": pitch, "wp": [tx, ty]}
                    if cam_pitch_pos is not None:
                        pose["cam_pitch"] = cam_pitch_pos.getValue()
                    if cam_roll_pos is not None:
                        pose["cam_roll"] = cam_roll_pos.getValue()
                    if cam_yaw_pos is not None:
                        pose["cam_yaw"] = cam_yaw_pos.getValue()
                    poses.append(pose)
                    # write poses.json after every waypoint so progress survives
                    # even if the run is cut short before the patrol completes
                    # (it is also what RESUME continues from after a crash).
                    json.dump(poses, open(POSES_FILE, "w"), indent=1)
                    print(f"[parkdrone] reached wp{idx} at ({x:.1f},{y:.1f}) "
                          f"-> frame_{idx:03d}.png")
                    if not SNAP_DIAG:
                        camera.disable()
                    wp_min = float("inf")
                    wp_steps = 0
                    idx += 1
                    if idx == len(wps):
                        print("[parkdrone] patrol complete")
                    elif abs(wrap(math.atan2(wps[idx][1] - y, wps[idx][0] - x)
                                  - yaw)) > HOLD_TURN:
                        hold_stop = True   # big turn ahead: stop, spin, then go
            elif arrived:
                camera.enable(dt)
                cam_warm = CAM_WARMUP
            else:
                # aim point: the current waypoint, blending toward the next one
                # as we close in, so the nose flows through waypoint hand-offs
                ax, ay = tx, ty
                if idx + 1 < len(wps) and dist < AIM_BLEND:
                    t_b = 1.0 - dist / AIM_BLEND
                    ax += (wps[idx + 1][0] - tx) * t_b
                    ay += (wps[idx + 1][1] - ty) * t_b
                # heading PD: point the nose at the aim point (steer like a car;
                # we do NOT strafe with roll, which would tumble the drone).
                yaw_err = wrap(math.atan2(ay - y, ax - x) - yaw)
                yaw_d = clamp(K_YAW * yaw_err - K_YAWD * yaw_rate, -1.0, 1.0)
                # Velocity-target forward control against the corner-aware
                # profile: the allowed speed decays along the kinematic
                # braking curve toward the current waypoint's limit (V_MAX on
                # straights -- no dip at hand-offs; V_TURN at corners --
                # arrive slow, turn tightly) and is 0 until we're facing the
                # aim point. Roll damps drift.
                if hold_stop:
                    # stop-and-turn: brake to a hover (yaw PD keeps spinning
                    # toward the new heading meanwhile), release once stopped.
                    if math.hypot(vx, vy) < HOLD_SPEED:
                        hold_stop = False
                    v_des = 0.0
                else:
                    v_des = (min(V_MAX,
                                 math.sqrt(wp_vmax[idx]**2 + 2 * A_BRAKE * dist))
                             if abs(yaw_err) < 0.5 else 0.0)
                pitch_d = -clamp(K_VEL * (v_des - fwd_vel), -TILT_MAX, TILT_MAX)
                roll_d = ROLL_SIGN * clamp(-K_VEL * lat_vel, -TILT_MAX, TILT_MAX)
        else:
            # Patrol done: station-keep by braking horizontal drift, otherwise the
            # drone slowly sails away (km-scale) with no control input.
            pitch_d = -clamp(-K_VEL * fwd_vel, -TILT_MAX, TILT_MAX)
            roll_d = ROLL_SIGN * clamp(-K_VEL * lat_vel, -TILT_MAX, TILT_MAX)

    # propeller mixing
    roll_in = K_ROLL * clamp(roll, -1, 1) + roll_rate + roll_d
    pitch_in = K_PITCH * clamp(pitch, -1, 1) + pitch_rate + pitch_d
    yaw_in = yaw_d
    vert = K_VP * clamp(TARGET_ALT - alt + K_VOFF, -1, 1) ** 3 - K_VD * vz

    motors[0].setVelocity(K_VT + vert - roll_in + pitch_in - yaw_in)   # front-left
    motors[1].setVelocity(-(K_VT + vert + roll_in + pitch_in + yaw_in))  # front-right
    motors[2].setVelocity(-(K_VT + vert - roll_in - pitch_in + yaw_in))  # rear-left
    motors[3].setVelocity(K_VT + vert + roll_in - pitch_in - yaw_in)   # rear-right
